// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpfltpgarjkvkijvjsdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZmx0cGdhcmprdmtpanZqc2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDcxNDgsImV4cCI6MjA3MjgyMzE0OH0.zqj8y2d4eWi_JQQI7ZN48j1U6jv_pEcKWKe7jCs37_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
<<<<<<< HEAD
});
=======
});
>>>>>>> d45c02f4aa1bfcdfaadb82d7f8c06fb23dd58f2d
